/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.lab4;

import java.io.FileInputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.tree.ParseTreeWalker;
import org.apache.commons.io.FilenameUtils;
import ru.nsu.fit.lab4.generated.MyLangLexer;
import ru.nsu.fit.lab4.generated.MyLangParser;

public class App {

  public static void main(String[] args) throws IOException {
    String filename;
    if (args.length >= 1) {
      filename = args[0];
    } else {
      System.out.println("File not provided");
      return;
    }

    String className = FilenameUtils.getBaseName(filename);

    MyLangLexer myLangLexer = new MyLangLexer(
    CharStreams.fromStream(new FileInputStream(filename)));
    MyLangParser myLangParser = new MyLangParser(new CommonTokenStream(myLangLexer));
    var tree = myLangParser.code();

    ParseTreeWalker walker = new ParseTreeWalker();
    MyLangListenerImpl listener = new MyLangListenerImpl(className);
    walker.walk(listener, tree);

    byte[] dump = listener.getBytes();

    Files.write(Paths.get(className + ".class"), dump);
    System.out.println(Paths.get(className + ".class").toAbsolutePath());
  }
}
